import type { Restaurant, RestaurantSignal } from '../types';

export const INITIAL_RESTAURANT_SIGNALS: RestaurantSignal[] = [
  // Delfina Signals
  {
    id: 'sig-del-1',
    restaurantId: 'rest-sf-1',
    restaurantName: 'Delfina Pizzeria',
    type: 'review_complaint',
    source: 'Yelp & Google Maps (SF Mission)',
    title: 'Customer Complaints: "2-Hour Wait Lines & No Reservations for Small Groups"',
    description: 'Scraped 24 recent Yelp reviews. Guests love the pizza but complain bitterly about 2-hour walk-in wait times on Valencia & 18th St, and zero gluten-free dough options.',
    detectedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    opportunityScore: 95,
    actionableInsight: 'Diners in the Mission are walking away due to 2-hour wait lines and missing gluten-free options at Delfina.',
    sourceUrl: 'https://yelp.com/biz/delfina-san-francisco',
  },
  {
    id: 'sig-del-2',
    restaurantId: 'rest-sf-1',
    restaurantName: 'Delfina Pizzeria',
    type: 'menu_price_change',
    source: 'Online Menu Scan',
    title: 'Raised Specialty Pizza Prices by +$4.00 (Now $28 Avg)',
    description: 'Neapolitan pizzas increased from $24 to $28 per pie, pushing average check cost up across Mission District diners.',
    detectedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    opportunityScore: 82,
    actionableInsight: 'Competitor price increases leave a sweet spot for a $20-$24 high-quality sourdough pizza menu.',
    sourceUrl: 'https://delfinasf.com',
  },

  // Flour + Water Signals
  {
    id: 'sig-fw-1',
    restaurantId: 'rest-sf-2',
    restaurantName: 'Flour + Water',
    type: 'menu_price_change',
    source: 'San Francisco Menu Scan',
    title: 'Mandatory 6% SF Health Mandate + 20% Service Charge Added',
    description: 'Yelp & Google reviews show guest frustration over added mandatory surcharges making pasta entrees effectively $42+ per person.',
    detectedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    opportunityScore: 88,
    actionableInsight: 'SF diners are tired of hidden surcharges on checks. Honest, transparent menu pricing builds instant local loyalty.',
    sourceUrl: 'https://flourandwater.com',
  },

  // Beretta Signals
  {
    id: 'sig-ber-1',
    restaurantId: 'rest-sf-3',
    restaurantName: 'Beretta',
    type: 'permit_expansion',
    source: 'SF City Planning Permits',
    title: 'Filed Outdoor Heated Parklet & Late-Night Cocktail License',
    description: 'SF Planning Department permit shows expansion of heated outdoor parklet seating on Valencia St with 1:00 AM weekend bar hours.',
    detectedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    opportunityScore: 78,
    actionableInsight: 'Late-night cocktail & outdoor parklet demand on Valencia St is surging. Consider an aperitivo hour program.',
    sourceUrl: 'https://sf.gov/permits',
  },

  // Taqueria La Cumbre Signal
  {
    id: 'sig-tac-1',
    restaurantId: 'rest-sf-4',
    restaurantName: 'Taqueria La Cumbre',
    type: 'new_opening',
    source: 'SF Health Department',
    title: 'Renovated Kitchen & Expanded Craft Beer Tap Lineup',
    description: 'Historic Mission burrito spot updated health permit and added 8 local craft beer taps.',
    detectedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    opportunityScore: 65,
    actionableInsight: 'Casual Mexican food brings steady foot traffic to Valencia St.',
    sourceUrl: 'https://sf.gov',
  },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-sf-1',
    name: 'Delfina Pizzeria',
    domain: 'delfinapizzeria.com',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80',
    cuisine: 'Italian & Wood-Fired Pizza',
    priceTier: '$$$',
    avgEntreePrice: 28,
    rating: 4.6,
    reviewCount: 1850,
    address: '3611 18th St, San Francisco',
    neighborhood: 'Mission District, SF (0.2 mi away)',
    distanceMiles: 0.2,
    status: 'Open & Active',
    opportunityLevel: 'HIGH COMPETITION',
    menuHighlights: [
      { name: 'Salsiccia Pizza (Hot Pepper & Sausage)', price: 28, category: 'Pizzas', isPopular: true },
      { name: 'Margherita Napoletana', price: 24, category: 'Pizzas', isPopular: true },
      { name: 'Arancini (Fried Risotto Balls)', price: 16, category: 'Appetizers & Starters' },
      { name: 'Aperol Spritz / Negroni', price: 16, category: 'Cocktails & Drinks' },
    ],
    customerDislikes: [
      '2-hour outdoor wait times on Friday & Saturday nights',
      'No reservations accepted for groups under 6 people',
      'Zero gluten-free or low-carb crust options on the menu',
      'Extremely loud dining room, hard to have a conversation',
    ],
    signals: INITIAL_RESTAURANT_SIGNALS.filter((s) => s.restaurantId === 'rest-sf-1'),
    primaryOpportunity: 'Accept online reservations & offer a 48-hour fermented gluten-free Neapolitan crust to capture turned-away diners from Delfina.',
    winningStrategy: 'Position your restaurant as "The Mission\'s cozy, reservable Neapolitan pizzeria with organic gluten-free options".',
  },
  {
    id: 'rest-sf-2',
    name: 'Flour + Water',
    domain: 'flourandwater.com',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&q=80',
    cuisine: 'Handmade Italian & Pasta Bar',
    priceTier: '$$$$',
    avgEntreePrice: 36,
    rating: 4.5,
    reviewCount: 2100,
    address: '2401 Harrison St, San Francisco',
    neighborhood: 'Mission District, SF (0.6 mi away)',
    distanceMiles: 0.6,
    status: 'Open & Active',
    opportunityLevel: 'MODERATE OVERLAP',
    menuHighlights: [
      { name: 'Handmade Cacio e Pepe', price: 32, category: 'Pastas', isPopular: true },
      { name: 'Squid Ink Agnolotti', price: 36, category: 'Pastas', isPopular: true },
      { name: 'Chef Pasta Tasting Menu', price: 125, category: 'Main Dishes' },
    ],
    customerDislikes: [
      'Mandatory 6% SF Health Mandate + 20% living wage fee added to check',
      'Very expensive ($150+ per couple), strictly special occasion',
      'Small pasta portion sizes for $30+ price tags',
    ],
    signals: INITIAL_RESTAURANT_SIGNALS.filter((s) => s.restaurantId === 'rest-sf-2'),
    primaryOpportunity: 'Provide generous, comforting pasta portions at a transparent $22-$26 price point without surprise health mandate fees.',
    winningStrategy: 'Highlight generous, handmade pasta plates with honest, flat pricing for weeknight dining.',
  },
  {
    id: 'rest-sf-3',
    name: 'Beretta',
    domain: 'berettasf.com',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    cuisine: 'Thin-Crust Pizza & Craft Cocktails',
    priceTier: '$$',
    avgEntreePrice: 26,
    rating: 4.5,
    reviewCount: 2900,
    address: '1199 Valencia St, San Francisco',
    neighborhood: 'Mission District, SF (0.4 mi away)',
    distanceMiles: 0.4,
    status: 'Open & Active',
    opportunityLevel: 'HIGH COMPETITION',
    menuHighlights: [
      { name: 'Burrata & Spicy Salami Pizza', price: 26, category: 'Pizzas', isPopular: true },
      { name: 'Pananna Cocktail', price: 16, category: 'Cocktails & Drinks', isPopular: true },
    ],
    customerDislikes: [
      'Cocktails take 20+ minutes at the bar during peak hours',
      'Very crowded and noisy outdoor parklet area',
    ],
    signals: INITIAL_RESTAURANT_SIGNALS.filter((s) => s.restaurantId === 'rest-sf-3'),
    primaryOpportunity: 'Fast cocktail service & comfortable outdoor seating to win over impatient weekend crowds.',
    winningStrategy: 'Offer a pre-batched craft cocktail program that serves drinks in under 2 minutes.',
  },
  {
    id: 'rest-sf-4',
    name: 'Taqueria La Cumbre',
    domain: 'taquerialacumbre.com',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80',
    cuisine: 'Mission Burritos & Tacos',
    priceTier: '$',
    avgEntreePrice: 14,
    rating: 4.4,
    reviewCount: 1650,
    address: '515 Valencia St, San Francisco',
    neighborhood: 'Mission District, SF (0.5 mi away)',
    distanceMiles: 0.5,
    status: 'Open & Active',
    opportunityLevel: 'BEST OPPORTUNITY',
    menuHighlights: [
      { name: 'Super Carne Asada Burrito', price: 15, category: 'Main Dishes', isPopular: true },
      { name: 'Al Pastor Tacos (3)', price: 12, category: 'Main Dishes' },
    ],
    customerDislikes: [
      'No indoor seated dining experience (mostly quick counter service)',
      'Cash-only or extra card fee',
    ],
    signals: INITIAL_RESTAURANT_SIGNALS.filter((s) => s.restaurantId === 'rest-sf-4'),
    primaryOpportunity: 'Complement casual taco traffic with a cozy sit-down evening dining spot.',
    winningStrategy: 'Drive Mission dinner traffic to your sit-down dining room.',
  },
  {
    id: 'rest-sf-5',
    name: 'Souvla',
    domain: 'souvla.com',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80',
    cuisine: 'Fast-Casual Greek & Frozen Yogurt',
    priceTier: '$$',
    avgEntreePrice: 18,
    rating: 4.6,
    reviewCount: 1980,
    address: '517 Hayes St, San Francisco',
    neighborhood: 'Hayes Valley, SF (1.1 mi away)',
    distanceMiles: 1.1,
    status: 'Open & Active',
    opportunityLevel: 'BEST OPPORTUNITY',
    menuHighlights: [
      { name: 'Roast Lamb Sandwich / Salad', price: 18, category: 'Main Dishes', isPopular: true },
      { name: 'Greek Frozen Yogurt w/ Baklava', price: 8, category: 'Appetizers & Starters' },
    ],
    customerDislikes: [
      'Counter service order lines spill onto sidewalk during lunch',
    ],
    signals: [],
    primaryOpportunity: 'Top performing neighborhood anchor model in Hayes Valley.',
    winningStrategy: 'Adopt Souvla\'s streamlined counter-to-table service model for high weekday turnover.',
  },
  {
    id: 'rest-sf-6',
    name: 'Che Fico',
    domain: 'chefico.com',
    imageUrl: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=400&q=80',
    cuisine: 'Rustic Italian & Natural Wine',
    priceTier: '$$$$',
    avgEntreePrice: 42,
    rating: 4.6,
    reviewCount: 1420,
    address: '838 Divisadero St, San Francisco',
    neighborhood: 'Alamo Square, SF (1.4 mi away)',
    distanceMiles: 1.4,
    status: 'Open & Active',
    opportunityLevel: 'MODERATE OVERLAP',
    menuHighlights: [
      { name: 'Pine Nut & Pork Sausage Pizza', price: 34, category: 'Pizzas', isPopular: true },
      { name: 'Suppli Modena', price: 18, category: 'Appetizers & Starters' },
    ],
    customerDislikes: [
      '10% SF Dine equity surcharge + high entree pricing makes it cost $200+ per couple',
    ],
    signals: [],
    primaryOpportunity: 'Capture local SF diners seeking rustic Italian without fine-dining pricing.',
    winningStrategy: 'Position your restaurant as "Everyday Italian comfort food for real San Franciscans".',
  },
];
